import { Inter } from "next/font/google";
import Link from "next/link";
import "../../public/bootstrap/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin StarBooking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css"
          rel="stylesheet"
        />
        <style>
          {`
            .sidebar {
              background-color: #ffffff;
              color: #152C5B;
              height: 100vh;
              position: fixed;
              overflow-y: auto;
              border-right: 1px solid #ddd;
              transition: all 0.3s ease;
            }
            .sidebar p {
              margin: 0;
              padding: 15px 20px;
              font-weight: normal;
              display: flex;
              align-items: center;
              color: #152C5B;
              transition: background-color 0.3s, color 0.3s;
              border-radius: 8px;
            }
            .sidebar p:hover {
              color: #fff;
              background-color: #1ABC9C;
              font-weight: bold;
            }
            .sidebar i {
              margin-right: 10px;
              transition: color 0.3s;
            }
            .sidebar p:hover i {
              color: #fff;
            }
            .header {
              background-color: #dee2e6;
              padding: 10px 20px;
              box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
              display: flex;
              justify-content: space-between;
              align-items: center;
            }
            .header p {
              margin: 0;
              font-size: 1.6rem;
              color: #152C5B;
              font-weight: bold;
            }
            .user-info {
              display: flex;
              align-items: center;
            }
            .user-info span {
              margin-right: 10px;
              color: #152C5B;
            }
            .user-info img {
              border-radius: 50%;
              border: 2px solid #152C5B;
            }
            .content-area {
              margin-left: 18%;
              padding: 30px;
              background-color: #f7f7f7;
              min-height: 100vh;
            }
            .sidebar h3 {
              font-size: 2rem;
              text-align: center;
              margin-bottom: 20px;
            }
            .sidebar hr {
              margin: 20px 0;
              border-color: #152C5B;
            }
            a {
              color: inherit;
              text-decoration: none;
            }

            @media (max-width: 991.98px) {
              .sidebar {
                width: 100%;
                height: auto;
                position: relative;
              }
              .content-area {
                margin-left: 0;
              }
              .header {
                padding: 10px;
              }
            }
          `}
        </style>
      </head>
      <body className={inter.className}>
        <div className="sidebar p-4">
          <h3 className="text-center">
            <span style={{ color: "#F4EA52", fontWeight: "bold" }}>STAR</span>
            <span style={{ color: "#152C5B", fontWeight: "bold" }}>
              Booking
            </span>
          </h3>
          <hr />
          <p>
            <i className="bi bi-house-fill"></i>
            <Link href="/">Dashboard</Link>
          </p>
          <p>
            <i className="bi bi-people-fill"></i>
            <Link href="/nguoidung">Quản lý người dùng</Link>
          </p>
          <p>
            <i className="bi bi-people-fill"></i>
            <Link href="/nhanvien">Quản lý nhân viên</Link>
          </p>
          <p>
            <i className="bi bi-chat-left-text-fill"></i>
            <Link href="/tintuc">Quản lý tin tuc</Link>
          </p>
          <p>
            <i className="bi bi-tag-fill"></i>
            <Link href="/danhmuc">Quản lý danh mục phòng</Link>
          </p>
          <p>
            <i className="bi bi-box-seam"></i>
            <Link href="/phong">Quản lý phòng</Link>
          </p>
          <p>
            <i className="bi bi-cart-fill"></i>
            <Link href="/donphong">Quản lý đơn đặt phòng</Link>
          </p>
          <p>
            <i className="bi bi-cart-fill"></i>
            <Link href="/dichvu">Quản lý dịch vụ</Link>
          </p>
          <p>
            <i className="bi bi-pie-chart-fill"></i>
            <Link href="/thongke">Quản lý thống kê</Link>
          </p>
          <p>
            <i className="bi bi-cart-fill"></i>
            <Link href="/trangthaiphong">Quản lý trạng thái phòng</Link>
          </p>
          <p>
            <i className="bi bi-chat-left-text-fill"></i>
            <Link href="/binhluan">Quản lý bình luận</Link>
          </p>
          <hr />
        </div>
        <div className="content-area">
          <div className="header" style={{ margin: "0 0 20px 5px" }}>
            <p>Quản Lý Hệ Thống StarBooking</p>
            <div className="user-info">
              <span>Admin</span>
              <img
                className="m-1"
                width="40"
                height="40"
                src="/images/admin.png"
                alt="Admin"
              />
            </div>
          </div>
          <div className="row">{children}</div>
        </div>
      </body>
    </html>
  );
}
